document.addEventListener("DOMContentLoaded", async () => {
  const lightbox = document.getElementById("lightbox");
  const lightboxImg = document.getElementById("lightbox-img");
  const lightboxCaption = document.getElementById("lightbox-caption");
  const lightboxPan = lightbox.querySelector(".lightbox-pan");
  const closeBtn = lightbox.querySelector(".lightbox-close");
  const zoomInBtn = lightbox.querySelector(".lightbox-zoom-in");
  const zoomOutBtn = lightbox.querySelector(".lightbox-zoom-out");
  const resetBtn = lightbox.querySelector(".lightbox-reset");
  const fullscreenBtn = lightbox.querySelector(".lightbox-fullscreen");
  const galleryGrid = document.getElementById("gallery-grid");

  let scale = 1;
  let posX = 0;
  let posY = 0;
  let isDragging = false;
  let startX, startY, startPosX, startPosY;

  function applyTransform() {
    lightboxPan.style.transform = `translate(${posX}px, ${posY}px) scale(${scale})`;
  }

  const lightboxPdf = document.getElementById("lightbox-pdf");
  const downloadBtn = lightbox.querySelector(".lightbox-download");

  let currentSrc = "";
  let currentCaption = "";
  let currentIsPdf = false;

  // Load assets from assets.json (generated by build.js)
  try {
    const res = await fetch("assets.json");
    const { images = [], pdfs = [] } = await res.json();
    galleryGrid.innerHTML = "";

    images.forEach(({ src, name }) => {
      const item = document.createElement("article");
      item.className = "gallery-item";
      item.dataset.src = src;
      item.dataset.alt = name;
      item.innerHTML = `<img src="${src}" alt="${name}"><span class="caption">${name}</span>`;
      galleryGrid.appendChild(item);
    });

    pdfs.forEach(({ src, name }) => {
      const item = document.createElement("article");
      item.className = "gallery-item gallery-item--pdf";
      item.dataset.type = "pdf";
      item.dataset.src = src;
      item.dataset.alt = name;
      item.innerHTML = `<div class="gallery-item-pdf-thumb"><span class="pdf-icon">PDF</span></div><span class="caption">${name}</span>`;
      galleryGrid.appendChild(item);
    });

    if (images.length === 0 && pdfs.length === 0) {
      galleryGrid.innerHTML = '<p class="gallery-empty">No assets found. Add images to assets/images/ and PDFs to assets/documents/, then run <code>node build.js</code>.</p>';
    }
  } catch (e) {
    galleryGrid.innerHTML = '<p class="gallery-empty">Run <code>node build.js</code> to generate assets.json, then refresh.</p>';
  }

  function openLightbox(src, alt, caption, isPdf = false) {
    currentSrc = src;
    currentCaption = caption;
    currentIsPdf = isPdf;
    lightboxCaption.textContent = caption;
    scale = 1;
    posX = 0;
    posY = 0;
    applyTransform();

    if (isPdf) {
      lightboxImg.src = "";
      lightboxImg.style.display = "none";
      lightboxPan.classList.add("is-hidden");
      lightboxPdf.src = src;
      lightboxPdf.classList.add("is-visible");
      lightbox.querySelector(".lightbox-toolbar").style.display = "none";
    } else {
      lightboxPdf.src = "";
      lightboxPdf.classList.remove("is-visible");
      lightboxPan.classList.remove("is-hidden");
      lightboxImg.src = src;
      lightboxImg.alt = alt;
      lightboxImg.style.display = "";
      lightbox.querySelector(".lightbox-toolbar").style.display = "flex";
    }

    lightbox.setAttribute("aria-hidden", "false");
    document.body.style.overflow = "hidden";
  }

  function closeLightbox() {
    lightboxPdf.src = "";
    lightboxPdf.classList.remove("is-visible");
    lightboxPan.classList.remove("is-hidden");
    lightbox.querySelector(".lightbox-toolbar").style.display = "flex";
    lightbox.setAttribute("aria-hidden", "true");
    document.body.style.overflow = "";
  }

  // Gallery item clicks (delegated - works for dynamically added items)
  galleryGrid.addEventListener("click", (e) => {
    const item = e.target.closest(".gallery-item");
    if (!item) return;
    const src = item.dataset.src || item.querySelector("img")?.src;
    const alt = item.dataset.alt || item.querySelector("img")?.alt || "";
    const caption = item.querySelector(".caption")?.textContent || alt;
    const isPdf = item.dataset.type === "pdf" || /\.pdf$/i.test(src || "");
    openLightbox(src, alt, caption, isPdf);
  });

  // Close
  closeBtn.addEventListener("click", closeLightbox);
  lightbox.addEventListener("click", (e) => {
    if (e.target === lightbox) closeLightbox();
  });
  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape" && lightbox.getAttribute("aria-hidden") === "false") {
      closeLightbox();
    }
  });

  // Zoom
  zoomInBtn.addEventListener("click", (e) => {
    e.stopPropagation();
    scale = Math.min(scale + 0.5, 5);
    applyTransform();
  });

  zoomOutBtn.addEventListener("click", (e) => {
    e.stopPropagation();
    scale = Math.max(scale - 0.5, 0.5);
    applyTransform();
  });

  resetBtn.addEventListener("click", (e) => {
    e.stopPropagation();
    scale = 1;
    posX = 0;
    posY = 0;
    applyTransform();
  });

  // Pan (drag)
  lightboxPan.addEventListener("mousedown", (e) => {
    if (scale <= 1) return;
    isDragging = true;
    startX = e.clientX;
    startY = e.clientY;
    startPosX = posX;
    startPosY = posY;
  });

  document.addEventListener("mousemove", (e) => {
    if (!isDragging) return;
    posX = startPosX + (e.clientX - startX);
    posY = startPosY + (e.clientY - startY);
    applyTransform();
  });

  document.addEventListener("mouseup", () => {
    isDragging = false;
  });

  // Touch support for zoom/pan on mobile
  lightboxPan.addEventListener("touchstart", (e) => {
    if (e.touches.length === 2) {
      e.preventDefault();
    } else if (e.touches.length === 1 && scale > 1) {
      startX = e.touches[0].clientX;
      startY = e.touches[0].clientY;
      startPosX = posX;
      startPosY = posY;
    }
  }, { passive: false });

  lightboxPan.addEventListener("touchmove", (e) => {
    if (e.touches.length === 1 && scale > 1) {
      posX = startPosX + (e.touches[0].clientX - startX);
      posY = startPosY + (e.touches[0].clientY - startY);
      applyTransform();
    }
  });

  // Mouse wheel zoom
  lightbox.addEventListener("wheel", (e) => {
    if (lightbox.getAttribute("aria-hidden") === "true") return;
    e.preventDefault();
    if (e.deltaY < 0) {
      scale = Math.min(scale + 0.2, 5);
    } else {
      scale = Math.max(scale - 0.2, 0.5);
    }
    applyTransform();
  }, { passive: false });

  // Download
  downloadBtn.addEventListener("click", (e) => {
    e.stopPropagation();
    if (!currentSrc) return;
    const ext = currentIsPdf ? ".pdf" : (currentSrc.match(/\.(svg|png|jpg|jpeg|webp)$/i)?.[0] || "");
    const filename = (currentCaption || "download").replace(/[^a-z0-9_-]/gi, "_") + ext;
    const a = document.createElement("a");
    a.href = currentSrc;
    a.download = filename;
    a.target = "_blank";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  });

  // Fullscreen
  fullscreenBtn.addEventListener("click", (e) => {
    e.stopPropagation();
    if (!document.fullscreenElement) {
      lightbox.requestFullscreen?.();
    } else {
      document.exitFullscreen?.();
    }
  });
});
